name: cache_restore
runs:
  using: composite
  steps:
    - uses: actions/cache/restore@v4
      with:
        path: |
          # See https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          # See https://doc.rust-lang.org/cargo/guide/build-cache.html
          target
        key: ${{ runner.os }}|${{ github.job }}|${{ github.run_attempt }}
        restore-keys: |
          ${{ runner.os }}|${{ github.job }}
          ${{ runner.os }}

