name: Coverage

on:
  push:
    branches: [ main ]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/**'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Setup | Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate code coverage
        run: cargo tarpaulin -p imap-codec -p imap-types --all-features --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

