on:
  push:
    branches: [ main ]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cache_restore
      - run: cargo install just
      - run: just coverage
      - uses: ./.github/actions/cache_save

      - uses: coverallsapp/github-action@c203f016dd0ff7855ebef0ed852000c20c117148
        with:
          format: lcov
          file: target/coverage/coverage.lcov
