on:
  push:
    branches: [ main ]
    paths:
      - "**.rs"
      - "**.toml"
      - ".github/workflows/**"
  pull_request:
    branches: [ main ]
    paths:
      - "**.rs"
      - "**.toml"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  minimal_versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cache_restore
      - run: cargo install just
      - run: just minimal_versions
      - uses: ./.github/actions/cache_save

