on:
  push:
    branches: [ main ]
    paths:
      - "**.rs"
      - "**.toml"
      - ".github/workflows/**"
  pull_request:
    branches: [ main ]
    paths:
      - "**.rs"
      - "**.toml"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  minimal_versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: cache-restore
        uses: actions/cache/restore@v4
        with:
          # See https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ github.workflow }}

      - run: cargo install just
      - run: just minimal_versions

      - id: cache-save
        uses: actions/cache/save@v4
        with:
          # See https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

